# Generated by Django 6.1.1 on 2026-10-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('power', 'Power'), ('phones', 'Phones'), ('laptops', 'Laptops'), ('tablets', 'Tablets')], db_index=True, default='phones', max_length=20),
        ),
    ]
